indentation fixed in all parts of the code

diff --git a/aur-repo b/aur-repo
--- a/aur-repo
+++ b/aur-repo
@@ -138,21 +138,21 @@ echo "---> $REPOPATH"
 
 # Check given path and show help
 if [ ! -f "${REPOPATH}/repo.conf" ]; then
-	show_help
-	exit 1
+    show_help
+    exit 1
 fi
 
 cd $REPOPATH
 if [ $? -eq 1 ]; then
-	exit 1
+    exit 1
 fi
 
 # Include the configuration
 source repo.conf
 
 if [ ${#GET_FROM_AUR[@]} -eq 0 ]; then
-	echo "Error in configuration or no packages specified."
-	exit 1
+    echo "Error in configuration or no packages specified."
+    exit 1
 fi
 
 if [ ! -d ".cache" ]; then
